# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NoteTaking' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NoteTaking
  pod 'RxSwift', '5.1.1'
  pod 'RxCocoa', '5.1.1'

  target 'NoteTakingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NoteTakingUITests' do
    # Pods for testing
  end

end
